data:
  data_path: "datasets/elliptic/elliptic_data.pt"
  weights_only: false

evaluation:
  percentiles: [90, 99, 99.9]

device: "cuda"

pretrained:
  checkpoint: "checkpoints"

dataset:
  type: elliptic
  kwargs: {}

results:
  path: "results/"